/* ============================================
   MYHBeauty — GitHub Sync
   --------------------------------------------
   Pushes the site data produced by the admin panel (products, page
   content, banners, category icons, blog posts, social links and every
   uploaded image — images ride inside data.js as embedded data URLs)
   straight into a GitHub repository, using GitHub's REST API from the
   browser. Nothing but GitHub receives anything; there is no server
   component and the access token never leaves the browser except in the
   Authorization header of requests to api.github.com.

   Exposes: window.GHSync
   ============================================ */
(function (global) {
  'use strict';

  var CONFIG_KEY = 'myh_github_sync_config';
  var LAST_KEY = 'myh_github_sync_last';
  var API_BASE = 'https://api.github.com';
  /* Practical guard rail: the contents endpoint accepts up to 100 MB,
     but anything past ~25 MB is a bad idea for a static site bundle. */
  var WARN_BYTES = 25 * 1024 * 1024;

  var DEFAULTS = {
    owner: 'zzbrabbit',
    repo: 'MYH-',
    branch: 'main',
    path: 'data.js',
    token: '',
    alsoImages: false,
    fileBased: false
  };

  /* ------------------------------------------------ storage helpers */
  function ls() {
    try { return global.localStorage; } catch (e) { return null; }
  }

  function readJSON(key) {
    var s = ls();
    if (!s) return null;
    try {
      var raw = s.getItem(key);
      return raw ? JSON.parse(raw) : null;
    } catch (e) { return null; }
  }

  function writeJSON(key, value) {
    var s = ls();
    if (!s) return false;
    try { s.setItem(key, JSON.stringify(value)); return true; } catch (e) { return false; }
  }

  function loadConfig() {
    var saved = readJSON(CONFIG_KEY) || {};
    var cfg = {};
    for (var k in DEFAULTS) {
      if (Object.prototype.hasOwnProperty.call(DEFAULTS, k)) {
        cfg[k] = (saved[k] !== undefined && saved[k] !== null) ? saved[k] : DEFAULTS[k];
      }
    }
    return cfg;
  }

  function saveConfig(cfg) {
    var merged = loadConfig();
    for (var k in DEFAULTS) {
      if (Object.prototype.hasOwnProperty.call(cfg, k)) merged[k] = cfg[k];
    }
    writeJSON(CONFIG_KEY, merged);
    return merged;
  }

  function loadLast() { return readJSON(LAST_KEY); }

  function saveLast(rec) { writeJSON(LAST_KEY, rec); return rec; }

  /* ------------------------------------------------ encoding helpers */
  /* UTF-8 safe base64 encoder (btoa alone chokes on non-Latin1 input). */
  function utf8ToBase64(str) {
    var bytes = new TextEncoder().encode(String(str));
    var chunk = 0x8000;
    var parts = [];
    for (var i = 0; i < bytes.length; i += chunk) {
      parts.push(String.fromCharCode.apply(null, bytes.subarray(i, i + chunk)));
    }
    return btoa(parts.join(''));
  }

  function base64ToUtf8(b64) {
    var bin = atob(b64);
    var bytes = new Uint8Array(bin.length);
    for (var i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    return new TextDecoder().decode(bytes);
  }

  /* Bytes of a UTF-8 string, without building a Blob (works in Node too). */
  function utf8Bytes(str) { return new TextEncoder().encode(String(str)).length; }

  /* ------------------------------------------------ bundle helpers */
  /* The exact text that must sit in the repository's data.js. */
  function buildDataJs(bundle) {
    return '/* MYHBeauty published data — generated by the admin panel.\n'
      + '   Committed by "Sync to GitHub" on ' + new Date().toISOString() + '.\n'
      + '   This file IS the site content: products, page content, banners,\n'
      + '   category icons, blog posts, social links and embedded images. */\n'
      + 'window.MYH_PUBLISHED_DATA = ' + JSON.stringify(bundle) + ';\n';
  }

  /* Deterministic short hash — used to make stable image file names so
     repeated pushes do not create a new file for an unchanged image. */
  function shortHash(str) {
    var h = 5381;
    for (var i = 0; i < str.length; i++) {
      h = ((h << 5) + h + str.charCodeAt(i)) >>> 0;  // h * 33 + c
    }
    return ('0000000' + h.toString(16)).slice(-8);
  }

  function extForMime(mime) {
    var m = String(mime || '').toLowerCase();
    if (m.indexOf('jpeg') !== -1) return 'jpg';
    if (m.indexOf('png') !== -1) return 'png';
    if (m.indexOf('webp') !== -1) return 'webp';
    if (m.indexOf('gif') !== -1) return 'gif';
    if (m.indexOf('svg') !== -1) return 'svg';
    return 'img';
  }

  /* Walk the whole bundle and pick up every embedded data:image/ URL.
     Returns [{ path, base64, mime, bytes }] — de-duplicated by content. */
  function collectImages(bundle, folder) {
    folder = folder || 'images/uploads';
    var seen = Object.create(null);
    var out = [];
    (function walk(node) {
      if (typeof node === 'string') {
        var m = /^data:(image\/[a-zA-Z0-9.+-]+);base64,([A-Za-z0-9+/=]+)$/.exec(node);
        if (!m) return;
        var payload = m[2];
        var hash = shortHash(payload);
        if (seen[hash]) return;
        seen[hash] = true;
        var bytes = payload.length - Math.floor(payload.length / 4);  // ≈ decoded size
        out.push({
          path: folder.replace(/^\/+|\/+$/g, '') + '/img-' + hash + '.' + extForMime(m[1]),
          mime: m[1],
          base64: payload,
          bytes: bytes
        });
      } else if (Array.isArray(node)) {
        for (var i = 0; i < node.length; i++) walk(node[i]);
      } else if (node && typeof node === 'object') {
        for (var k in node) {
          if (Object.prototype.hasOwnProperty.call(node, k)) walk(node[k]);
        }
      }
    })(bundle);
    return out;
  }

  /* ------------------------------------------------ GitHub REST layer */
  function contentsUrl(cfg, path) {
    var owner = encodeURIComponent(cfg.owner);
    var repo = encodeURIComponent(cfg.repo);
    var clean = String(path || '').replace(/\\/g, '/').replace(/^\/+/, '');
    var encoded = clean.split('/').map(function (seg) { return encodeURIComponent(seg); }).join('/');
    return API_BASE + '/repos/' + owner + '/' + repo + '/contents/' + encoded;
  }

  function describeError(status, payload, ghHeaders) {
    ghHeaders = ghHeaders || {};
    var sso = ghHeaders['x-github-sso'] || '';
    var scopes = ghHeaders['x-oauth-scopes'] || '';
    var msg = (payload && payload.message) ? payload.message : ('HTTP ' + status);
    if (status === 401) {
      msg = 'GitHub rejected the token (401): ' + msg
        + '. The token is invalid, revoked or expired — generate a fresh one and paste it again.';
    } else if (status === 403) {
      if (sso) {
        msg = 'GitHub rejected the request (403): ' + msg
          + '. This repository belongs to an organization that enforces SAML SSO, and the token is not '
          + 'authorized for it. Fix: GitHub → Settings → Developer settings → Personal access tokens → '
          + 'open the token → "Configure SSO" → Authorize it for that organization, then retry.';
      } else {
        msg = 'GitHub rejected the request (403): ' + msg + '. '
          + 'The token can SEE the repo but cannot WRITE its contents. ';
        if (scopes) {
          msg += 'Its scopes are [' + scopes + '] — the write scope is missing. ';
        }
        msg += 'Fix: use a CLASSIC token with "repo" ticked (full control of private repos; "public_repo" '
          + 'alone is NOT enough for a private repo), OR a FINE-GRAINED token whose settings grant '
          + '"Contents: Read and write" and access to this repository.';
      }
    } else if (status === 404) {
      msg = 'Not found (404): owner/repo or the branch name may be wrong, or the token has no access '
        + 'to this repository.';
    } else if (status === 409) {
      msg = 'Conflict (409): ' + msg + '. The file may have changed since it was read — please push again.';
    } else if (status === 422) {
      msg = 'Unprocessable (422): ' + msg + '. Usually an invalid path or an empty/invalid token.';
    }
    return msg;
  }

  /* Read the GitHub-specific response headers (lower-cased by fetch). */
  function readGhHeaders(res) {
    var h = {};
    try {
      h['x-oauth-scopes'] = res.headers.get('x-oauth-scopes') || '';
      h['x-github-sso'] = res.headers.get('x-github-sso') || '';
      h['retry-after'] = res.headers.get('retry-after') || '';
    } catch (e) { /* ignore */ }
    return h;
  }

  function request(method, url, token, body) {
    var headers = {
      'Accept': 'application/vnd.github+json',
      'Authorization': 'Bearer ' + token,
      'X-GitHub-Api-Version': '2022-11-28'
    };
    var opts = { method: method, headers: headers };
    if (body) {
      headers['Content-Type'] = 'application/json';
      opts.body = JSON.stringify(body);
    }
    return fetch(url, opts).then(function (res) {
      var ghHeaders = readGhHeaders(res);
      return res.json().catch(function () { return {}; }).then(function (payload) {
        if (!res.ok) {
          var err = new Error(describeError(res.status, payload, ghHeaders));
          err.status = res.status;
          err.payload = payload;
          err.ghHeaders = ghHeaders;
          throw err;
        }
        return payload;
      });
    });
  }

  /* sha of the existing file, or null when it does not exist yet. */
  function getFileSha(cfg, path) {
    var url = contentsUrl(cfg, path) + '?ref=' + encodeURIComponent(cfg.branch);
    return request('GET', url, cfg.token).then(function (meta) {
      return meta && meta.sha ? meta.sha : null;
    }).catch(function (e) {
      if (e.status === 404) return null;
      throw e;
    });
  }

  /* Upload one file. contentBase64 must already be base64 of the bytes. */
  function putFile(cfg, path, contentBase64, message) {
    return getFileSha(cfg, path).then(function (sha) {
      var body = {
        message: message,
        content: contentBase64,
        branch: cfg.branch
      };
      if (sha) body.sha = sha;
      return request('PUT', contentsUrl(cfg, path), cfg.token, body).then(function (res) {
        var url = (res && res.content && res.content.html_url)
          || (res && res.commit && res.commit.html_url)
          || '';
        return {
          path: path,
          url: url,
          action: sha ? 'updated' : 'created',
          bytes: Math.floor(contentBase64.length * 3 / 4)
        };
      });
    });
  }

  function testConnection(cfg) {
    if (!cfg.token) throw new Error('Please paste a GitHub access token first.');
    var url = API_BASE + '/repos/' + encodeURIComponent(cfg.owner) + '/' + encodeURIComponent(cfg.repo);
    return request('GET', url, cfg.token).then(function (repo) {
      return {
        fullName: repo.full_name,
        private: !!repo.private,
        defaultBranch: repo.default_branch,
        hasPush: !!(repo.permissions && (repo.permissions.push || repo.permissions.admin))
      };
    });
  }

  /* Inspect the token itself (independent of any repository): who it
     belongs to, whether it is classic or fine-grained, and which scopes it
     carries. This is the authoritative pre-flight for write access. */
  function inspectToken(cfg) {
    if (!cfg.token) throw new Error('Please paste a GitHub access token first.');
    var url = API_BASE + '/user';
    var headers = {
      'Accept': 'application/vnd.github+json',
      'Authorization': 'Bearer ' + cfg.token,
      'X-GitHub-Api-Version': '2022-11-28'
    };
    return fetch(url, { method: 'GET', headers: headers }).then(function (res) {
      var scopes = (res.headers.get('x-oauth-scopes') || '')
        .split(',').map(function (s) { return s.trim(); }).filter(Boolean);
      var out = {
        status: res.status,
        login: '',
        scopes: scopes,
        type: scopes.length ? 'classic' : 'fine-grained',
        sso: !!res.headers.get('x-github-sso'),
        error: ''
      };
      return res.json().catch(function () { return {}; }).then(function (u) {
        if (!res.ok) {
          out.error = (u && u.message) ? u.message : ('HTTP ' + res.status);
          return out;
        }
        out.login = u.login || '';
        /* A classic token writes contents with "repo" (private) or
           "public_repo" (public). A fine-grained token cannot be checked
           from the header — it must have "Contents: Read and write" set in
           its own settings, which we surface as a reminder rather than a pass. */
        out.canWriteContents = out.type === 'fine-grained'
          ? null  /* unknown from header — needs the setting to be correct */
          : scopes.some(function (s) { return s === 'repo' || s === 'public_repo'; });
        return out;
      });
    });
  }

  /* Put it all together: push the bundle (and optionally images) to GitHub. */
  function push(cfg, bundle, opts) {
    opts = opts || {};
    if (!cfg.owner || !cfg.repo) throw new Error('Repository owner and name are required.');
    if (!cfg.token) throw new Error('Please paste a GitHub access token first.');

    var js = buildDataJs(bundle);
    var size = utf8Bytes(js);
    var results = { files: [], dataBytes: size, imageBytes: 0, warnings: [] };
    if (size > WARN_BYTES) {
      results.warnings.push('data.js is ' + Math.round(size / 1048576) + ' MB — that is heavy for a '
        + 'static bundle. Compress your product images in the admin (they are down-scaled on upload) '
        + 'or use the "images/ folder" option to keep the bundle smaller later.');
    }

    var stamp = new Date().toISOString().replace('T', ' ').slice(0, 19);
    var message = (opts.message || ('Update site data from admin — ' + stamp));
    var chain = putFile(cfg, cfg.path, utf8ToBase64(js), message).then(function (rec) {
      results.files.push(rec);
      if (!cfg.alsoImages) return results;
      var assets = collectImages(bundle, opts.imageFolder || 'images/uploads');
      results.imageCount = assets.length;
      var i = 0;
      return (function next() {
        if (i >= assets.length) return results;
        var img = assets[i++];
        return putFile(cfg, img.path, img.base64, 'Add image ' + img.path + ' — ' + stamp)
          .then(function (r) {
            results.files.push(r);
            results.imageBytes += img.bytes;
          })
          .catch(function (e) {
            results.warnings.push(img.path + ': ' + e.message);
          })
          .then(next);
      })();
    });
    return chain.then(function (r) {
      var head = r.files[0];
      saveLast({
        time: new Date().toLocaleString(),
        url: head ? head.url : '',
        repo: cfg.owner + '/' + cfg.repo,
        branch: cfg.branch,
        path: cfg.path,
        files: r.files.length,
        bytes: r.dataBytes + (r.imageBytes || 0)
      });
      return r;
    });
  }

  /* Static files that make up the site itself. Used by "Push Whole Site",
     which reads each file from the running site (same origin) and commits
     it, so the repository always mirrors what is online. */
  var SITE_MANIFEST = [
    'index.html', 'about.html', 'products.html', 'treatments.html', 'blog.html',
    'contact.html', 'admin.html', 'login.html', '404.html', 'deploy-guide.html',
    'css/style.css', 'css/admin.css',
    'js/main.js', 'js/store.js', 'js/admin.js', 'js/github-sync.js',
    'sitemap.xml', 'robots.txt', 'favicon.svg'
  ];

  /* Read one file served alongside this admin page. */
  function fetchText(path) {
    return fetch(path, { cache: 'no-store' }).then(function (res) {
      if (!res.ok) throw new Error('cannot read ' + path + ' (HTTP ' + res.status + ')');
      return res.text();
    });
  }

  /* Commit every static file + the fresh data.js bundle. */
  function pushSite(cfg, bundle, paths, opts) {
    opts = opts || {};
    if (!cfg.owner || !cfg.repo) throw new Error('Repository owner and name are required.');
    if (!cfg.token) throw new Error('Please paste a GitHub access token first.');

    var list = (paths && paths.length) ? paths.slice() : SITE_MANIFEST.slice();
    var results = { files: [], warnings: [], skipped: [], dataBytes: 0, imageBytes: 0 };
    if (bundle) results.dataBytes = utf8Bytes(buildDataJs(bundle));
    var stamp = new Date().toISOString().replace('T', ' ').slice(0, 19);

    var i = 0;
    return (function next() {
      if (i >= list.length) return results;
      var rel = list[i++];
      /* data.js is written from the live bundle below, skip it in the sweep. */
      if (rel.replace(/^\/+/, '') === String(cfg.path || '').replace(/^\/+/, '')) {
        results.skipped.push(rel);
        return next();
      }
      return fetchText(rel).then(function (text) {
        return putFile(cfg, rel, utf8ToBase64(text), 'Site file ' + rel + ' — ' + stamp)
          .then(function (r) { results.files.push(r); });
      }).catch(function (e) {
        results.warnings.push(rel + ': ' + e.message);
      }).then(next);
    })().then(function () {
      if (!bundle) return results;
      return push(cfg, bundle, opts).then(function (r) {
        results.files = r.files.concat(results.files);
        results.warnings = results.warnings.concat(r.warnings || []);
        results.dataBytes = r.dataBytes;
        results.imageBytes = r.imageBytes;
        results.imageCount = r.imageCount;
        return results;
      });
    }).then(function (r) {
      saveLast({
        time: new Date().toLocaleString(),
        url: (r.files[0] ? r.files[0].url : ''),
        repo: cfg.owner + '/' + cfg.repo,
        branch: cfg.branch,
        path: cfg.path,
        files: r.files.length,
        bytes: r.dataBytes + (r.imageBytes || 0),
        wholeSite: true
      });
      return r;
    });
  }

  /* ------------------------------------------------ file-based storage
     Split the single data.js blob into a small index (data.js) plus real
     image files (images/) and per-item content files (content/...). The
     repository then holds content as ordinary, diff-able files instead of
     one ever-growing base64 blob. The live site opts into this via the
     `fileBased` flag in data.js (see store.js). */

  function itemId(item, type, i) {
    if (item && item.id) return String(item.id);
    if (item && item.slug) return String(item.slug);
    if (item && item.title) {
      var s = String(item.title).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
      if (s) return s;
    }
    return type + '-' + (i + 1);
  }

  /* Compact card-level summary kept inside data.js so listings render
     without fetching every content file up front. */
  function pickListing(item, type) {
    var listing = { id: item.id, type: type };
    ['title', 'slug', 'excerpt', 'summary', 'category', 'categories', 'tags', 'date', 'cover', 'image', 'status']
      .forEach(function (k) {
        if (item[k] !== undefined && item[k] !== null) listing[k] = item[k];
      });
    if (!listing.cover && item.image) listing.cover = item.image;
    if (!listing.cover && Array.isArray(item.gallery) && item.gallery[0]) listing.cover = item.gallery[0];
    return listing;
  }

  /* Collect every embedded data: URL, recording a repo-relative path for
     each unique one. Returns { assets:[{path,mime,base64,bytes}], map }. */
  function splitImages(bundle, imgFolder) {
    imgFolder = (imgFolder || 'images').replace(/^\/+|\/+$/g, '');
    var map = Object.create(null);
    var assets = [];
    (function walk(node) {
      if (typeof node === 'string') {
        var m = /^data:(image\/[a-zA-Z0-9.+-]+);base64,([A-Za-z0-9+/=]+)$/.exec(node);
        if (!m) return;
        var payload = m[2];
        if (map[payload]) return;
        map[payload] = imgFolder + '/img-' + shortHash(payload) + '.' + extForMime(m[1]);
        assets.push({
          path: map[payload],
          mime: m[1],
          base64: payload,
          bytes: payload.length - Math.floor(payload.length / 4)
        });
      } else if (Array.isArray(node)) {
        node.forEach(walk);
      } else if (node && typeof node === 'object') {
        for (var k in node) {
          if (Object.prototype.hasOwnProperty.call(node, k)) walk(node[k]);
        }
      }
    })(bundle);
    return { assets: assets, map: map };
  }

  /* Deep-clone, replacing each embedded data: URL with its repo-relative path. */
  function rewriteImageUrls(node, map) {
    if (typeof node === 'string') {
      var m = /^data:(image\/[a-zA-Z0-9.+-]+);base64,([A-Za-z0-9+/=]+)$/.exec(node);
      if (m && map[m[2]]) return map[m[2]];
      return node;
    } else if (Array.isArray(node)) {
      return node.map(function (n) { return rewriteImageUrls(n, map); });
    } else if (node && typeof node === 'object') {
      var out = {};
      for (var k in node) {
        if (Object.prototype.hasOwnProperty.call(node, k)) out[k] = rewriteImageUrls(node[k], map);
      }
      return out;
    }
    return node;
  }

  /* Build the full set of repository files for file-based storage.
     Each item: { path, text (utf8 JSON) OR base64 (raw bytes), message }. */
  function buildFileSet(bundle, opts) {
    opts = opts || {};
    var imgFolder = (opts.imageFolder || 'images').replace(/^\/+|\/+$/g, '');
    var contentFolder = (opts.contentFolder || 'content').replace(/^\/+|\/+$/g, '');

    var split = splitImages(bundle, imgFolder);
    var light = rewriteImageUrls(bundle, split.map);
    var files = [];

    split.assets.forEach(function (a) {
      files.push({ path: a.path, base64: a.base64, message: 'Add image ' + a.path });
    });

    var products = Array.isArray(light.products) ? light.products : [];
    var posts = Array.isArray(light.posts) ? light.posts : [];

    products.forEach(function (p, i) {
      var id = itemId(p, 'product', i);
      files.push({
        path: contentFolder + '/products/' + id + '.json',
        text: JSON.stringify(p, null, 2),
        message: 'Product ' + id
      });
    });
    posts.forEach(function (p, i) {
      var id = itemId(p, 'post', i);
      files.push({
        path: contentFolder + '/posts/' + id + '.json',
        text: JSON.stringify(p, null, 2),
        message: 'Post ' + id
      });
    });

    var index = {
      version: 1,
      fileBased: true,
      publishedAt: new Date().toISOString(),
      social: light.social,
      banners: light.banners,
      catnav: light.catnav,
      content: light.content,
      msgForwardEmail: light.msgForwardEmail,
      products: products.map(function (p, i) { return pickListing(p, 'product'); }),
      posts: posts.map(function (p, i) { return pickListing(p, 'post'); })
    };
    var dataJs = '/* MYHBeauty published index — file-based storage.\n'
      + '   Generated by the admin panel "Push as files" on ' + new Date().toISOString() + '.\n'
      + '   Products/posts live in content/ as JSON; images live in images/. */\n'
      + 'window.MYH_PUBLISHED_DATA = ' + JSON.stringify(index) + ';\n';
    files.push({ path: 'data.js', text: dataJs, message: 'Update index data.js (file-based)' });

    return files;
  }

  /* Commit a set of files sequentially. opts.onProgress(file, index, total)
     is invoked before each upload; opts.message stamps the commits. */
  function pushFileSet(cfg, files, opts) {
    opts = opts || {};
    if (!cfg.owner || !cfg.repo) throw new Error('Repository owner and name are required.');
    if (!cfg.token) throw new Error('Please paste a GitHub access token first.');

    var results = { files: [], warnings: [], imageBytes: 0, dataBytes: 0 };
    var stamp = new Date().toISOString().replace('T', ' ').slice(0, 19);
    var common = (opts.message || ('Update site content (file-based) — ' + stamp));
    var i = 0;
    return (function next() {
      if (i >= files.length) return results;
      var f = files[i++];
      var content = f.base64 ? f.base64 : utf8ToBase64(f.text || '');
      if (f.path === 'data.js') results.dataBytes += utf8Bytes(f.text || '');
      else if (f.base64) results.imageBytes += (f.bytes || Math.floor(f.base64.length * 3 / 4));
      if (typeof opts.onProgress === 'function') {
        try { opts.onProgress(f, i - 1, files.length); } catch (e) { /* ignore */ }
      }
      return putFile(cfg, f.path, content, (f.message || ('Add ' + f.path)) + ' — ' + stamp)
        .then(function (r) { results.files.push(r); })
        .catch(function (e) { results.warnings.push(f.path + ': ' + e.message); })
        .then(next);
    })().then(function (r) {
      saveLast({
        time: new Date().toLocaleString(),
        url: (r.files[0] ? r.files[0].url : ''),
        repo: cfg.owner + '/' + cfg.repo,
        branch: cfg.branch,
        path: cfg.path,
        files: r.files.length,
        bytes: r.dataBytes + (r.imageBytes || 0),
        fileBased: true
      });
      return r;
    });
  }

  global.GHSync = {
    SITE_MANIFEST: SITE_MANIFEST,
    API_BASE: API_BASE,
    DEFAULTS: DEFAULTS,
    CONFIG_KEY: CONFIG_KEY,
    LAST_KEY: LAST_KEY,
    loadConfig: loadConfig,
    saveConfig: saveConfig,
    loadLast: loadLast,
    saveLast: saveLast,
    utf8ToBase64: utf8ToBase64,
    base64ToUtf8: base64ToUtf8,
    utf8Bytes: utf8Bytes,
    buildDataJs: buildDataJs,
    shortHash: shortHash,
    collectImages: collectImages,
    contentsUrl: contentsUrl,
    getFileSha: getFileSha,
    putFile: putFile,
    testConnection: testConnection,
    inspectToken: inspectToken,
    fetchText: fetchText,
    push: push,
    pushSite: pushSite,
    buildFileSet: buildFileSet,
    pushFileSet: pushFileSet
  };
})(typeof window !== 'undefined' ? window : globalThis);
